### ISSUE TITLE
不显示图标

### ISSUE THREAD

**Issue by luyuan2002** [pinky-pig/vue3-hot-toast#2]
![image](https://github.com/user-attachments/assets/e494eb79-1fc1-47f6-bf0a-02028eaa3c58)
所有图标均不显示，环境：win11 vue：`3.2.37` vite：`3.0.7`
```typescript
import toast, {Toaster} from 'vue3-hot-toast'

Auth(form.platform, form.userName, form.userPwd), {
  loading: '登录中...',
  success: '登录成功！',
  error: (msg: string) => msg,
}
```

```html
<Toaster/>
```

**Comment by 6owen** [comment]
多谢，0.0.5 version 解决了，这几个图标是用伪元素模拟的😂。
这有个在线示例，vue：3.2.37 vite：3.0.7 。
https://stackblitz.com/edit/vitejs-vite-eysxej?file=src%2FApp.vue

**Comment by luyuan2002** [comment]
> 多谢，0.0.5 version 解决了，这几个图标是用伪元素模拟的😂。 这有个在线示例，vue：3.2.37 vite：3.0.7 。 https://stackblitz.com/edit/vitejs-vite-eysxej?file=src%2FApp.vue

好的感谢！
